title = "Roket"
gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
tagline = "Roblox game framework built to skyroket your developer experience!"